# Generated by Django 4.2.16 on 2024-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Imagen', null=True, upload_to='media/products'),
        ),
    ]
