# Generated by Django 4.2.16 on 2024-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_post_price_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Imagen', upload_to='products/'),
        ),
    ]
